In [1]:
from calendar import error

import numpy as np
from tensorflow.python.ops.summary_ops_v2 import record_if

In [2]:
ratings = np.array([
    [5,3,0,1],
    [4,0,0,1],
    [1,1,0,5],
    [1,0,0,4],
    [0,1,5,4]
])
ratings

array([[5, 3, 0, 1],
       [4, 0, 0, 1],
       [1, 1, 0, 5],
       [1, 0, 0, 4],
       [0, 1, 5, 4]])

In [4]:
num_users,num_items=ratings.shape
num_users

5

In [5]:
num_items

4

In [6]:
num_factors=2
learning_rate=0.01
num_epoches=1000

In [7]:
user_matrix=np.random.rand(num_users,num_factors)
user_matrix

array([[0.38431241, 0.43295133],
       [0.24859719, 0.05678113],
       [0.7375491 , 0.40863122],
       [0.74087149, 0.25644672],
       [0.28669228, 0.61607248]])

In [8]:
item_matrix=np.random.rand(num_factors,num_items)
item_matrix

array([[0.0208154 , 0.7782876 , 0.99304363, 0.03297582],
       [0.70514031, 0.5080225 , 0.06693026, 0.81025629]])

In [9]:
for epoch in range(num_epoches):
    for i in range(num_users):
        for j in range(num_items):
            if ratings[i][j]>0:
                error=ratings[i][j]-np.dot(user_matrix[i,:],item_matrix[:,j])
                user_matrix[i,:]+=learning_rate*(error*item_matrix[:,j])
                item_matrix[:,j]+=learning_rate*(error*user_matrix[i,:])
predicted_ratings=np.dot(user_matrix,item_matrix)            

In [11]:
recommended_items=[]
for i in range(num_users):
    recommended_items.append(np.argsort(predicted_ratings[i])[::-1])

In [12]:
recommended_items

[array([0, 1, 2, 3]),
 array([0, 2, 1, 3]),
 array([2, 3, 0, 1]),
 array([2, 3, 0, 1]),
 array([2, 3, 0, 1])]